"""KD-10: blindspot finder.

For each district, 1994-2024 (ERA5 series), find thirstwave days (days inside runs of >= 3
flagged ET0 days) where Tmax stayed below (a) its own day-of-year p90 and (b) fixed 37/38/39/40 C
heat thresholds. A "blindspot event" = a whole thirstwave run during which Tmax never exceeded the
threshold, i.e. a heat alert based on that threshold would have stayed silent the entire time.
April 2024 is never presented as a blindspot (Tmax was above its p90 on most days).

Writes data/out/blindspot_report.md and data/out/blindspot_events.json.
"""
import json

from common import OUT, RAW, district_ids, load_daily
from thirstcast_core.detection import find_runs, flag_days

FIXED = (37, 38, 39, 40)


def load_clim(did):
    return [c for c in json.loads((OUT / "climatology.json").read_text()) if c["district"] == did]


def analyse(did):
    rows = load_daily(RAW / f"archive_{did}_1994_2023.json") + load_daily(RAW / f"archive_{did}_2024.json")
    days = flag_days(rows, load_clim(did))
    runs = find_runs([d["flag"] for d in days])
    events, wave_days = [], 0
    counts = {"below_p90": 0, **{f"below_{t}": 0 for t in FIXED}}
    for s, e in runs:
        run = days[s:e + 1]
        wave_days += len(run)
        counts["below_p90"] += sum(not d["tmax_flag"] for d in run)
        for t in FIXED:
            counts[f"below_{t}"] += sum(d["tmax"] < t for d in run)
        events.append({
            "district": did, "start": run[0]["date"], "end": run[-1]["date"], "days": len(run),
            "excess_mm": round(sum(d["excess_mm"] for d in run), 2),
            "max_tmax": max(d["tmax"] for d in run),
            "tmax_days_above_p90": sum(d["tmax_flag"] for d in run),
            "max_tmax_minus_p90": round(max(d["tmax"] - d["tmax_p90"] for d in run), 1),
            "all_below_p90": not any(d["tmax_flag"] for d in run),
        })
    return events, wave_days, counts


def main():
    lines = ["# Blindspot report (KD-10)", "",
             "Generated by `data/scripts/blindspot_finder.py` (ERA5 `era5_seamless` series, 1994-2024, "
             "thresholds from `data/out/climatology.json`).", "",
             "A **blindspot event** is a whole thirstwave (run of 3+ days with ET0 above its day-of-year p90) "
             "during which Tmax never went above the heat threshold, so a temperature-based alert would have "
             "stayed silent for the entire event. Fixed thresholds 37-40 C are the range given in the source plan.", "",
             "## Thirstwave days by Tmax condition", "",
             "| District | Thirstwave runs | Thirstwave days | Tmax < own p90 | Tmax < 37 C | < 38 C | < 39 C | < 40 C |",
             "|---|---|---|---|---|---|---|---|"]
    all_events = []
    for did in district_ids("all"):
        ev, n, c = analyse(did)
        all_events += ev
        lines.append(f"| {did} | {len(ev)} | {n} | {c['below_p90']} | {c['below_37']} | {c['below_38']} | {c['below_39']} | {c['below_40']} |")
    blind = [e for e in all_events if e["all_below_p90"]]
    blind.sort(key=lambda e: (-e["days"], -e["excess_mm"]))
    lines += ["", f"## Blindspot events: whole thirstwave with Tmax at or below its own p90 every day ({len(blind)} found)", ""]
    if blind:
        lines += ["| District | Start | End | Days | ET0 excess (mm) | Max Tmax (C) | Max Tmax minus p90 (C) |",
                  "|---|---|---|---|---|---|---|"]
        for e in blind[:25]:
            lines.append(f"| {e['district']} | {e['start']} | {e['end']} | {e['days']} | {e['excess_mm']} | {e['max_tmax']} | {e['max_tmax_minus_p90']} |")
        if len(blind) > 25:
            lines.append(f"| ... | {len(blind) - 25} more in `blindspot_events.json` | | | | | |")
        best = blind[0]
        lines += ["", f"**Best candidate:** {best['district']}, {best['start']} to {best['end']}: a {best['days']}-day "
                  f"thirstwave (+{best['excess_mm']} mm ET0 above p90) while Tmax peaked at {best['max_tmax']} C and never "
                  f"exceeded its own day-of-year p90. A heat alert keyed to Tmax p90 (or to 37-40 C) would have said nothing.", ""]
        summer = [e for e in blind if e["start"][5:7] in ("03", "04", "05")]
        if summer:
            sb = summer[0]
            lines += [f"**Best hot-season (Mar-May) candidate:** {sb['district']}, {sb['start']} to {sb['end']}: "
                      f"{sb['days']} days, +{sb['excess_mm']} mm ET0 above p90, Tmax peaked at {sb['max_tmax']} C "
                      f"(never above its p90). Suggested for the blindspot slide because it falls in the irrigation-critical "
                      f"hot season.", ""]
        lines += ["Caveats: 1994-2023 events are in-sample (they are part of the climatology); ERA5 at a district "
                  "centroid (~10 km grid); Tmax p90 is a statistical threshold, not an official IMD heatwave criterion.", ""]
    else:
        lines += ["None found. Pitch the quantification layer honestly (source rule).", ""]
    a24 = [e for e in all_events if e["start"] <= "2024-04-30" and e["end"] >= "2024-04-01"]
    lines += ["## April 2024 is NOT a blindspot", "",
              "Thirstwave runs overlapping April 2024 and how many of their days also had Tmax above its p90:", "",
              "| District | Start | End | Days | Tmax > p90 days |", "|---|---|---|---|---|"]
    for e in a24:
        lines.append(f"| {e['district']} | {e['start']} | {e['end']} | {e['days']} | {e['tmax_days_above_p90']} |")
    lines.append("")
    (OUT / "blindspot_report.md").write_text("\n".join(lines))
    (OUT / "blindspot_events.json").write_text(json.dumps(all_events, indent=1) + "\n")
    print("\n".join(lines[:40]))


if __name__ == "__main__":
    main()
